[Database]
MySQLString = "root:root@/ExpertHubAuth"
RedisAddress = "localhost:6379"

[Server]
Port = ":811"

[User]
EmailAddress = "ExpertHubAuth@gmail.com"
EmailPassword = "Expert.Hub"
EmailHost = "smtp.gmail.com:587"